### ISSUE TITLE
Howto use ButtonV2 with multiple buttons.

### ISSUE THREAD

**Issue by mcmellow** [AndrewMascolo/ButtonV2#1]
Hi,

Ho can I use your library ButtonV2 with multiple buttons. I hope you can point me in the right direction.
Kind regards
MCMelloW

**Comment by AndrewMascolo** [comment]
If you are knowledgeable with c++, you can use arrays to go through all the buttons you want.

However if you are not then you would need to write everything out the long way. The example sketch is just for one button, but you can copy everything (aside from the button’s pin and object name).

**Comment by AndrewMascolo** [comment]
Try this. 

#include<ButtonV2.h>
#define numOfButtons 2

ButtonV2 buttonArray[numOfButtons];

const byte ButtonPins[numOfButtons] = {2, 3};

void setup()
{
  //pinMode(LEDpin, OUTPUT);
  pinMode(ButtonPin, INPUT_PULLUP);
  Serial.begin(115200);
  for(byte n = 0; n < numOfButtons; n++)
    buttonArray[n].SetStateAndTime(LOW);
  Serial.println("ready");
}

void loop()
{
  static byte i = 0;

  byte type = buttonArray[i].CheckButton(ButtonPins[i]); // current time and length of time to press the button as many times as you can ie. 1.5 seconds
  switch (type)
  {
    case WAITING:
      break;

```
case PRESSED:
  Serial.println("pressed 1 time");
  break;

case DOUBLE_PRESSED:
  Serial.println("pressed 2 times");
  break;

case MULTI_PRESSED:
  Serial.println("pressed 3 times");
  break;

case HELD:
  Serial.println("Button HELD");
  break;
```

  }

  i++; 
  if(i > (numOfButtons - 1) )
    i = 0;
}
